source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AFZalandoSDK_Example', :exclusive => true do
  pod 'AFZalandoSDK', :path => '../'
end

target 'AFZalandoSDK_Tests', :exclusive => true do
  pod 'AFZalandoSDK', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
